import axios from "axios";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [users, setUsers] = useState([]);

  const get_users = () => {
    axios
      .get("http://localhost:3001/api/users")
      .then((res) => setUsers(res.data.users))
      .catch((err) => console.log(err));
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div className={styles.btnContainer}>
          <button onClick={get_users} className={styles.btn}>
            CLICK ME
          </button>
        </div>
        <ul>
          {users.map((v, i) => (
            <li key={i}>{v.name}</li>
          ))}
        </ul>
      </main>
    </div>
  );
}
